name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Usa un entorno Ubuntu en GitHub Actions

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4.2.2

    - name: Setup Android SDK Tools
      uses: actions/setup-android@v3.2.2

    - name: Install required dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential
        sudo apt install -y android-sdk
        sudo apt install -y git

    - name: Build with ndk-build
      run: |
        cd jni
        ndk-build
